# Generated by Django 5.1.2 on 2024-10-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('individual_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneticData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_id', models.CharField(max_length=255)),
                ('chromosome', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=255)),
                ('reference_allele', models.CharField(max_length=10)),
                ('alternate_allele', models.CharField(max_length=10)),
                ('alternate_frequency', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('individual_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetic_data.individual')),
            ],
        ),
    ]
